# Generated by Django 3.0 on 2020-10-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='course',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='course',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='course',
            name='target_audience',
        ),
        migrations.AddField(
            model_name='course',
            name='bureau',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
