# Generated by Django 3.0 on 2020-10-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_correlation', '0001_initial'),
        ('course', '0004_auto_20201013_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='competencies',
        ),
        migrations.AddField(
            model_name='course',
            name='course_correlations',
            field=models.ManyToManyField(related_name='course_relations', to='course_correlation.CourseCorrelation'),
        ),
    ]
