# Generated by Django 3.0 on 2020-10-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competency_correlation', '0001_initial'),
        ('environment', '0002_auto_20190520_0649'),
        ('competency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='competency_correlations',
            field=models.ManyToManyField(related_name='competency_relations', to='competency_correlation.CompetencyCorrelation'),
        ),
        migrations.AddField(
            model_name='competency',
            name='environment',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competency_relation', to='environment.Environment'),
        ),
        migrations.AlterUniqueTogether(
            name='competency',
            unique_together={('environment', 'name')},
        ),
    ]
