# Generated by Django 3.0 on 2020-10-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0002_auto_20201012_1603'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competency',
            unique_together=set(),
        ),
    ]
