# Generated by Django 3.0 on 2020-10-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competency', '0003_auto_20201013_2214'),
        ('course', '0004_auto_20201013_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCorrelation',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('correlation', models.FloatField(null=True)),
                ('competency', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coursecorrelation_relation', to='competency.Competency')),
                ('course', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coursecorrelation_relation', to='course.Course')),
            ],
            options={
                'verbose_name': 'course correlation',
                'verbose_name_plural': 'course correlations',
                'db_table': 'course_competency_recommendation_system_course_correlation',
                'ordering': ['-correlation'],
                'abstract': False,
                'unique_together': {('course', 'competency')},
            },
        ),
    ]
